In [1]:
import pandas as pd

# Read CSV file into a DataFrame
df = pd.read_csv('Fallecidos_COVID_en_Colombia_20241106.csv')

# Display the first few rows
print("First 5 rows:")
print(df.head())

First 5 rows:
     fecha reporte web  ID de caso Fecha de notificación  \
0  2020-12-24 00:00:00     1556982   2020-12-22 00:00:00
1  2020-12-24 00:00:00     1556986   2020-12-18 00:00:00
2  2020-11-08 00:00:00     1137434   2020-11-05 00:00:00
3  2020-11-08 00:00:00     1137440   2020-11-03 00:00:00
4  2020-11-08 00:00:00     1137443   2020-11-04 00:00:00

   Código DIVIPOLA departamento Nombre departamento  \
0                            76               VALLE
1                            76               VALLE
2                            11              BOGOTA
3                            63             QUINDIO
4                            11              BOGOTA

   Código DIVIPOLA municipio Nombre municipio  Edad  Unidad de medida de edad  \
0                      76001             CALI    74                         1
1                      76001             CALI    66                         1
2                      11001           BOGOTA    81                         1
3                      63001          ARMENIA    85                         1
4                      11001           BOGOTA    78                         1

  Sexo  ... Código ISO del país Nombre del país Recuperado  \
0    F  ...                 NaN             NaN  Fallecido
1    F  ...                 NaN             NaN  Fallecido
2    F  ...                 NaN             NaN  Fallecido
3    F  ...                 NaN             NaN  Fallecido
4    M  ...                 NaN             NaN  Fallecido

   Fecha de inicio de síntomas      Fecha de muerte Fecha de diagnóstico  \
0          2020-12-17 00:00:00  2020-12-30 00:00:00  2020-12-23 00:00:00
1          2020-12-11 00:00:00  2020-12-26 00:00:00  2020-12-22 00:00:00
2          2020-10-31 00:00:00  2020-11-11 00:00:00  2020-11-07 00:00:00
3          2020-10-31 00:00:00  2020-11-12 00:00:00  2020-10-31 00:00:00
4          2020-10-31 00:00:00  2020-11-16 00:00:00  2020-11-07 00:00:00

  Fecha de recuperación Tipo de recuperación Pertenencia étnica  \
0                   NaN                  NaN                  6
1                   NaN                  NaN                  6
2                   NaN                  NaN                  6
3                   NaN                  NaN                  6
4                   NaN                  NaN                  6

   Nombre del grupo étnico
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN

[5 rows x 23 columns]

In [2]:
df

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
0,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,...,NaN,NaN,Fallecido,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,NaN
1,2020-12-24 00:00:00,1556986,2020-12-18 00:00:00,76,VALLE,76001,CALI,66,1,F,...,NaN,NaN,Fallecido,2020-12-11 00:00:00,2020-12-26 00:00:00,2020-12-22 00:00:00,NaN,NaN,6,NaN
2,2020-11-08 00:00:00,1137434,2020-11-05 00:00:00,11,BOGOTA,11001,BOGOTA,81,1,F,...,NaN,NaN,Fallecido,2020-10-31 00:00:00,2020-11-11 00:00:00,2020-11-07 00:00:00,NaN,NaN,6,NaN
3,2020-11-08 00:00:00,1137440,2020-11-03 00:00:00,63,QUINDIO,63001,ARMENIA,85,1,F,...,NaN,NaN,Fallecido,2020-10-31 00:00:00,2020-11-12 00:00:00,2020-10-31 00:00:00,NaN,NaN,6,NaN
4,2020-11-08 00:00:00,1137443,2020-11-04 00:00:00,11,BOGOTA,11001,BOGOTA,78,1,M,...,NaN,NaN,Fallecido,2020-10-31 00:00:00,2020-11-16 00:00:00,2020-11-07 00:00:00,NaN,NaN,6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143120,2021-10-23 00:00:00,4989604,2021-10-20 00:00:00,5,ANTIOQUIA,5001,MEDELLIN,82,1,M,...,NaN,NaN,Fallecido,2021-10-16 00:00:00,2021-10-22 00:00:00,2021-10-20 00:00:00,NaN,NaN,6,NaN
143121,2021-09-10 00:00:00,4926325,2021-09-07 00:00:00,47,MAGDALENA,47460,NUEVA GRANADA,92,1,F,...,NaN,NaN,Fallecido,2021-09-07 00:00:00,2021-09-29 00:00:00,2021-09-09 00:00:00,NaN,NaN,6,NaN
143122,2021-09-10 00:00:00,4926172,2021-09-08 00:00:00,76,VALLE,76834,TULUA,85,1,M,...,NaN,NaN,Fallecido,2021-09-02 00:00:00,2021-09-25 00:00:00,2021-09-08 00:00:00,NaN,NaN,6,NaN
143123,2021-10-24 00:00:00,4990109,2021-10-23 00:00:00,76,VALLE,76834,TULUA,81,1,M,...,NaN,NaN,Fallecido,2021-10-17 00:00:00,2021-10-27 00:00:00,2021-10-23 00:00:00,NaN,NaN,6,NaN
143124,2021-10-24 00:00:00,4990117,2021-10-22 00:00:00,76,VALLE,76834,TULUA,53,1,M,...,NaN,NaN,Fallecido,2021-10-16 00:00:00,2021-11-03 00:00:00,2021-10-22 00:00:00,NaN,NaN,6,NaN

In [3]:

# Get basic statistics
print("\nBasic Statistics:")
print(df.describe())

Basic Statistics:
         ID de caso  Código DIVIPOLA departamento  Código DIVIPOLA municipio  \
count  1.431250e+05                 143125.000000              143125.000000
mean   2.661864e+06                   1278.113369               33386.606707
std    1.739699e+06                   6045.118127               27409.352429
min    1.520000e+02                      5.000000                5001.000000
25%    1.161795e+06                     11.000000               11001.000000
50%    2.574208e+06                     25.000000               20001.000000
75%    3.964056e+06                     68.000000               63190.000000
max    6.388321e+06                  47001.000000               99773.000000

                Edad  Unidad de medida de edad  Código ISO del país  \
count  143125.000000             143125.000000            94.000000
mean       68.477939                  1.000936           583.702128
std        15.572765                  0.032789           335.247712
min         1.000000                  1.000000             4.000000
25%        59.000000                  1.000000           218.000000
50%        70.000000                  1.000000           840.000000
75%        80.000000                  1.000000           862.000000
max       112.000000                  3.000000          1000.000000

       Fecha de recuperación  Tipo de recuperación  Pertenencia étnica
count                    0.0                   0.0       143125.000000
mean                     NaN                   NaN            5.894526
std                      NaN                   NaN            0.645620
min                      NaN                   NaN            1.000000
25%                      NaN                   NaN            6.000000
50%                      NaN                   NaN            6.000000
75%                      NaN                   NaN            6.000000
max                      NaN                   NaN            6.000000

In [3]:
df["Recuperado"].unique()

array(['Fallecido', 'fallecido'], dtype=object)

In [14]:
df["fecha reporte web"].unique()[0]

'2020-12-24 00:00:00'

In [4]:
df["Tipo de recuperación"].unique()

array([nan])

In [9]:
df["Tipo de recuperación"].isna().sum() / df["Tipo de recuperación"].shape[0]
# => All ar NaN

np.float64(1.0)

In [7]:
total_deaths = df.shape[0]
print(f"Total deaths: {total_deaths:,}")

Total deaths: 143,125

In [10]:
# Convert the date columns to datetime 
df['Fecha de muerte'] = pd.to_datetime(df['Fecha de muerte']) 
# Find the range of dates 
earliest_death = df['Fecha de muerte'].min() 
latest_death = df['Fecha de muerte'].max() 
print(f"Range of death dates: {earliest_death.date()} to {latest_death.date()}")

Range of death dates: 2020-03-15 to 2024-01-12

In [16]:
df.isna().sum()

fecha reporte web                    0
ID de caso                           0
Fecha de notificación                0
Código DIVIPOLA departamento         0
Nombre departamento                  0
Código DIVIPOLA municipio            0
Nombre municipio                     0
Edad                                 0
Unidad de medida de edad             0
Sexo                                 0
Tipo de contagio                     0
Ubicación del caso                   0
Estado                               0
Código ISO del país             143031
Nombre del país                 143031
Recuperado                           0
Fecha de inicio de síntomas          0
Fecha de muerte                      0
Fecha de diagnóstico               124
Fecha de recuperación           143125
Tipo de recuperación            143125
Pertenencia étnica                   0
Nombre del grupo étnico         140830
dtype: int64